import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function Introduction() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-4xl font-extrabold tracking-tight text-foreground mb-8">
        About World Models Research Hub
      </h1>
      
      <div className="space-y-8">
        <Card className="bg-card/50 backdrop-blur-sm border-border">
          <CardHeader>
            <CardTitle className="text-2xl text-primary">Project Origin</CardTitle>
          </CardHeader>
          <CardContent className="text-lg text-muted-foreground leading-relaxed">
            <div className="flex items-center flex-wrap gap-2">
              <span>This AI-native academic website was generated by</span>
              <span className="inline-flex items-center gap-2 px-2 py-1 bg-accent/50 rounded-full border border-border/50">
                <img 
                  src="/avatar.png" 
                  alt="Steinerxxx" 
                  className="w-8 h-8 rounded-full border border-border object-cover"
                  onError={(e) => {
                    // Fallback if image is missing
                    e.currentTarget.style.display = 'none';
                  }} 
                />
                <strong className="text-foreground">Steinerxxx</strong>
              </span>
              <span>, a student from <strong>Tongji University</strong>, utilizing the power of <strong>Trae</strong> IDE.</span>
            </div>
            <p className="mt-4">
              The goal of this project is to provide researchers with an automated, up-to-date, and intelligent hub for tracking the latest advancements in World Models and related fields.
            </p>
          </CardContent>
        </Card>

        <Card className="bg-card/50 backdrop-blur-sm border-border">
          <CardHeader>
            <CardTitle className="text-2xl text-primary">Technical Architecture</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h3 className="font-semibold text-foreground mb-2">Frontend</h3>
                <ul className="list-disc list-inside text-muted-foreground space-y-1">
                  <li>React 19 + TypeScript</li>
                  <li>Vite for build tooling</li>
                  <li>Tailwind CSS + shadcn/ui for styling</li>
                  <li>Framer Motion for animations</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-2">Backend</h3>
                <ul className="list-disc list-inside text-muted-foreground space-y-1">
                  <li>Node.js + Express</li>
                  <li>PostgreSQL (Supabase)</li>
                  <li>Cheerio for arXiv scraping</li>
                  <li>Automated classification algorithms</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-2">Automation</h3>
                <ul className="list-disc list-inside text-muted-foreground space-y-1">
                  <li>Cron jobs for scheduled scraping (Every 6 hours)</li>
                  <li>Keyword-based multi-label classification</li>
                  <li>Precise date parsing and deduplication</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-2">Deployment</h3>
                <ul className="list-disc list-inside text-muted-foreground space-y-1">
                  <li>Frontend & Backend on Render/Vercel</li>
                  <li>Supabase Connection Pooling</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
