import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { motion, AnimatePresence } from 'framer-motion';
import { 
  X, 
  Monitor, 
  Server, 
  Cloud, 
  Database, 
  Code2
} from 'lucide-react';

interface TechNode {
  id: string;
  label: string;
  icon: React.ReactNode;
  description: string;
  details: string[];
  color: string;
}

const techNodes: TechNode[] = [
  {
    id: 'frontend',
    label: 'Frontend',
    icon: <Monitor className="w-6 h-6" />,
    description: 'Modern, responsive UI built for speed and accessibility.',
    details: ['React 19', 'TypeScript', 'Vite', 'Tailwind CSS', 'Framer Motion'],
    color: 'bg-blue-500'
  },
  {
    id: 'backend',
    label: 'Backend',
    icon: <Server className="w-6 h-6" />,
    description: 'Robust server-side logic handling data processing and APIs.',
    details: ['Node.js', 'Express', 'Cheerio Scraper', 'REST API'],
    color: 'bg-green-500'
  },
  {
    id: 'data',
    label: 'Data & AI',
    icon: <Database className="w-6 h-6" />,
    description: 'Intelligent data management and automated classification.',
    details: ['PostgreSQL (Supabase)', 'Automated Tagging', 'Keyword Analysis'],
    color: 'bg-purple-500'
  },
  {
    id: 'deployment',
    label: 'Deployment',
    icon: <Cloud className="w-6 h-6" />,
    description: 'Scalable cloud infrastructure ensuring high availability.',
    details: ['Vercel (Frontend)', 'Render (Backend)', 'CI/CD Pipelines'],
    color: 'bg-orange-500'
  }
];

export default function Introduction() {
  const [isAvatarZoomed, setIsAvatarZoomed] = useState(false);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);

  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-4xl font-extrabold tracking-tight text-foreground mb-8">
        About World Models Research Hub
      </h1>
      
      <div className="space-y-8">
        <Card className="bg-card/50 backdrop-blur-sm border-border overflow-hidden">
          <CardHeader>
            <CardTitle className="text-2xl text-primary">Project Origin</CardTitle>
          </CardHeader>
          <CardContent className="text-lg text-muted-foreground leading-relaxed">
            <div className="flex items-center flex-wrap gap-2">
              <span>This AI-native academic website was generated by</span>
              <span className="inline-flex items-center gap-2 px-2 py-1 bg-accent/50 rounded-full border border-border/50">
                <motion.div
                  layoutId="avatar"
                  onClick={() => setIsAvatarZoomed(true)}
                  className="cursor-pointer"
                  whileHover={{ scale: 1.1 }}
                >
                  <img 
                    src="/avatar.png" 
                    alt="Steinerxxx" 
                    className="w-8 h-8 rounded-full border border-border object-cover"
                    onError={(e) => {
                      e.currentTarget.style.display = 'none';
                    }} 
                  />
                </motion.div>
                <strong className="text-foreground">Steinerxxx</strong>
              </span>
              <span>, a student from <strong>Tongji University</strong>, utilizing the power of <strong>Trae</strong> IDE.</span>
            </div>
            <p className="mt-4">
              The goal of this project is to provide researchers with an automated, up-to-date, and intelligent hub for tracking the latest advancements in World Models and related fields.
            </p>
          </CardContent>
        </Card>

        {/* Interactive Mind Map */}
        <Card className="bg-card/50 backdrop-blur-sm border-border">
          <CardHeader>
            <CardTitle className="text-2xl text-primary flex items-center gap-2">
              <Code2 className="w-6 h-6" /> Technical Architecture
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground mb-6">
              Click on any node below to explore the technologies powering this platform.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 items-start">
              {techNodes.map((node) => (
                <motion.div
                  key={node.id}
                  layout
                  onClick={() => setSelectedNode(selectedNode === node.id ? null : node.id)}
                  className={`
                    relative p-4 rounded-xl border cursor-pointer overflow-hidden
                    ${selectedNode === node.id ? 'bg-accent/10 border-primary ring-1 ring-primary/50' : 'bg-card/30 border-border hover:border-primary/50'}
                    transition-colors
                  `}
                  initial={{ borderRadius: 12 }}
                >
                  <div className="flex items-start gap-4">
                    <div className={`p-3 rounded-lg ${node.color} text-white shadow-lg`}>
                      {node.icon}
                    </div>
                    <div className="flex-1">
                      <h3 className="font-bold text-foreground text-lg">
                        {node.label}
                      </h3>
                      <p className="text-sm text-muted-foreground mt-1">
                        {node.description}
                      </p>
                    </div>
                  </div>

                  <AnimatePresence>
                    {selectedNode === node.id && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="mt-4 pt-4 border-t border-border/50"
                      >
                        <ul className="grid grid-cols-2 gap-2">
                          {node.details.map((detail, idx) => (
                            <motion.li
                              key={detail}
                              initial={{ opacity: 0, x: -10 }}
                              animate={{ opacity: 1, x: 0 }}
                              transition={{ delay: idx * 0.1 }}
                              className="flex items-center gap-2 text-sm text-foreground/80"
                            >
                              <div className={`w-1.5 h-1.5 rounded-full ${node.color}`} />
                              {detail}
                            </motion.li>
                          ))}
                        </ul>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Avatar Zoom Modal */}
      <AnimatePresence>
        {isAvatarZoomed && (
          <div 
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm"
            onClick={() => setIsAvatarZoomed(false)}
          >
            <motion.div
              layoutId="avatar"
              className="relative max-w-lg w-full aspect-square bg-transparent"
              onClick={(e) => e.stopPropagation()}
            >
              <img 
                src="/avatar.png" 
                alt="Steinerxxx" 
                className="w-full h-full object-contain rounded-2xl shadow-2xl"
              />
              <button 
                onClick={() => setIsAvatarZoomed(false)}
                className="absolute -top-12 right-0 text-white hover:text-gray-300 transition-colors"
              >
                <X className="w-8 h-8" />
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
